name: Deploy Challenges

on:
  push:
    branches:
      - main
  paths:
    - "challenges/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy Challenge
        run: |
          for dir in $(find challenges/$CTF_YEAR -type d -mindepth 1 -maxdepth 1); do
            challenge=$(basename "$dir")
            if [ -f "$dir/Dockerfile" ]; then
              ssh ubuntu@<k8s_vm_ip> "kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: $challenge
spec:
  containers:
    - name: $challenge
      image: $(docker build -q -t $challenge $dir)
      ports:
        - containerPort: 1337
EOF"
            fi
          done
